all: build


build:
	mvn clean install package

run:
	java -jar target/fl-0.1-jar-with-dependencies.jar tests/test1.txt
	java -jar target/fl-0.1-jar-with-dependencies.jar tests/test2.txt
	java -jar target/fl-0.1-jar-with-dependencies.jar tests/test3.txt

